# Generated by Django 5.1.1 on 2024-09-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('suppliers', '0003_remove_suppliers_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
    ]
