# Generated by Django 5.1.1 on 2024-12-12 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_deliverypincode_user_id'),
        ('suppliers', '0004_suppliers_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
