# Generated by Django 5.1.1 on 2024-12-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_suppliers_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='account_created_by',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
