# Generated by Django 5.1.1 on 2024-12-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_suppliers_account_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
