# Generated by Django 5.1 on 2024-10-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_deliverypincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypincode',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
