# Generated by Django 5.1 on 2024-10-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_deliverypincode_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypincode',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
