# Generated by Django 5.1.1 on 2024-09-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_stock', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('storage_location', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batches.batches')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
            ],
        ),
    ]
