# Generated by Django 5.1.1 on 2024-09-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='batch_id',
        ),
    ]
