# Generated by Django 5.1.1 on 2024-09-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
        ('suppliers', '0004_suppliers_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='supplier_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppliers'),
        ),
    ]
