# Generated by Django 5.1.1 on 2024-09-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicine_supplier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='total_amount',
        ),
    ]
