# Generated by Django 5.1.1 on 2024-09-15 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('medicine', '0003_remove_medicine_total_amount'),
        ('orders', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ORDERED', 'ORDERED'), ('SHIPPED', 'SHIPPED'), ('DISPATCHED', 'DISPATCHED'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=15),
        ),
    ]
