# Generated by Django 5.1.1 on 2024-09-15 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('medicine', '0003_remove_medicine_total_amount'),
        ('orders', '0003_orders_cid_orders_product_alter_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='orders',
            name='credit_card_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='orders',
            name='cvv',
            field=models.CharField(default='111', max_length=3),
        ),
        migrations.AddField(
            model_name='orders',
            name='expiry_date',
            field=models.CharField(default='222', max_length=7),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_alternate_phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_landmark',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_postal_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
    ]
