# Generated by Django 5.1 on 2024-09-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_update_at_orders_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='supplier_id',
        ),
    ]
